---
- name: Update apt
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 600

- name: Install System Packages
  become: yes
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - git
    - curl
    - htop
    - ufw
